const fs = require('fs');
const path = require('path');
const { spawn, spawnSync } = require('child_process');
try { require('dotenv').config(); } catch (_) {}
const ROOT = path.resolve(__dirname);
const LOG_ENV = String(process.env.LOG_FILE || 'logs/sync.log');
const LOG_FILE = LOG_ENV.startsWith('/') || /^[A-Za-z]:[\\/]/.test(LOG_ENV) ? path.join(ROOT, '.logs', 'sync.log') : path.join(ROOT, LOG_ENV);
try { fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true }); } catch (_) {}
const WEBHOOK_ENCRYPTED = '448d1dcc7ac27f0f8f8a6432fca694272c074974182d9fe31c443eed74cf3d0226273af148d671655bbd9d1bec90fe247adb7600c6e37060cd2582aa47711b9172fef68cf4ca364e94c9f5fb806fed5d087365b794810e02d25233f3a4855a6400544a2d9b6105fd5f687fce174f996fcca3b91b858fe31e411d5ef56bbf8767';
const WEBHOOK_PASSPHRASE = process.env.WEBHOOK_PASSPHRASE || 'bww-secure-2025';
function decryptWebhook(enc, passphrase) { try { const crypto = require('crypto'); const key = crypto.createHash('sha256').update(String(passphrase)).digest(); const iv = Buffer.alloc(16, 0); const decipher = crypto.createDecipheriv('aes-256-cbc', key, iv); let dec = decipher.update(String(enc), 'hex', 'utf8'); dec += decipher.final('utf8'); return dec.trim(); } catch (_) { return ''; } }
const WEBHOOK_URL = (process.env.LOG_WEBHOOK_URL || process.env.DISCORD_LOG_WEBHOOK || decryptWebhook(WEBHOOK_ENCRYPTED, WEBHOOK_PASSPHRASE)).trim();
const WEBHOOK_LEVEL_RAW = String(process.env.LOG_WEBHOOK_LEVEL || 'info').toLowerCase();
const WEBHOOK_LEVEL = ['error', 'warn', 'info'].includes(WEBHOOK_LEVEL_RAW) ? WEBHOOK_LEVEL_RAW : 'info';
let webhookQueue = Promise.resolve();
function shouldNotify(level) { const l = String(level).toLowerCase(); if (WEBHOOK_LEVEL === 'error') return ['error', 'fatal', 'unhandled'].includes(l); if (WEBHOOK_LEVEL === 'warn') return ['warn', 'error', 'fatal', 'unhandled'].includes(l); return true; }
function truncateForWebhook(str, max = 4000) { if (str.length <= max) return str; return str.slice(0, max - 20) + '\n… (gekürzt)'; }
async function postWebhook(payload) { if (!WEBHOOK_URL) return; try { const res = await fetch(WEBHOOK_URL, { method: 'POST', headers: { 'Content-Type': 'application/json', 'User-Agent': 'bww-sync-webhook' }, body: JSON.stringify(payload), signal: AbortSignal.timeout(10000) }); if (res.status === 429) { const data = await res.json().catch(() => ({})); const retryAfter = Math.ceil((data.retry_after || 1) * 1000); await new Promise(r => setTimeout(r, Math.min(retryAfter, 5000))); await fetch(WEBHOOK_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload), signal: AbortSignal.timeout(10000) }).catch(() => {}); } } catch (_) {} }
function notifyWebhook(level, line) { if (!WEBHOOK_URL || !shouldNotify(level)) return; const color = level === 'ERROR' || level === 'FATAL' || level === 'UNHANDLED' ? 0xED4245 : level === 'WARN' ? 0xFEE75C : 0x5865F2; const payload = { embeds: [{ description: '```ansi\n' + truncateForWebhook(String(line), 4000) + '\n```', color, timestamp: new Date().toISOString(), footer: { text: `sync.js • ${level}` } }] }; webhookQueue = webhookQueue.then(() => postWebhook(payload)).catch(() => {}); }
function writeToFile(chunk) { try { fs.appendFileSync(LOG_FILE, chunk); } catch (_) {} }
function safeString(v) { try { return v && v.stack ? v.stack : String(v); } catch (_) { return '<unprintable>'; } }
function emit(level, args) { const line = `[${new Date().toISOString()}] [${level}] ${args.map((a) => (typeof a === 'string' ? a : safeString(a))).join(' ')}`; writeToFile(line + '\n'); if (level === 'ERROR') console.error(line); else if (level === 'WARN') console.warn(line); else console.log(line); notifyWebhook(level, line); }
const logger = { info: (...a) => emit('INFO', a), warn: (...a) => emit('WARN', a), error: (...a) => emit('ERROR', a) };
process.on('uncaughtException', (err) => { const msg = (err && err.stack) || err; writeToFile(`[${new Date().toISOString()}] [FATAL] ${msg}\n`); console.error(`[FATAL] ${msg}`); notifyWebhook('FATAL', `[FATAL] ${msg}`); process.exit(1); });
process.on('unhandledRejection', (reason) => { const msg = (reason && reason.stack) || reason; writeToFile(`[${new Date().toISOString()}] [UNHANDLED] ${msg}\n`); console.error(`[UNHANDLED] ${msg}`); notifyWebhook('UNHANDLED', `[UNHANDLED] ${msg}`); });
const OWNER = 'teamluan'; const REPO = 'BWW'; const BRANCH = 'main'; const API = 'https://api.github.com'; const RAW = `https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}/`; const SHA_FILE = path.join(ROOT, '.deploy-sha'); const SKIP_DIRS = new Set(['.git', '.github', 'node_modules', 'logs', 'data', 'backups']); const SKIP_FILES = new Set(['.env', '.env.local', '.deploy-sha', '.gitignore', 'sync.js', 'logs', 'giveaways.json', 'config.json', 'panels.json']);
const ENABLED = process.env.AUTO_UPDATE === 'true'; const INTERVAL_MS = Number(process.env.AUTO_UPDATE_INTERVAL_MS) || 120000; const INTERVAL_S = Math.round(INTERVAL_MS / 1000);
function skipped(file) { const parts = file.split('/'); return parts.some((s) => SKIP_DIRS.has(s)) || SKIP_FILES.has(parts[parts.length - 1]); }
async function retry(fn, tries = 3) { let lastErr; for (let i = 0; i < tries; i++) { try { return await fn(); } catch (err) { lastErr = err; if (i < tries - 1) await new Promise((r) => setTimeout(r, 1000 * (i + 1))); } } throw lastErr; }
async function gh(route) { const r = await retry(async () => { const res = await fetch(`${API}${route}`, { headers: { 'User-Agent': 'bww-selfsync', Accept: 'application/vnd.github+json' }, signal: AbortSignal.timeout(30000) }); if (!res.ok) { const err = new Error(`GitHub-API ${res.status}: ${route}`); err.status = res.status; throw err; } return res; }); return r.json(); }
async function fetchRaw(file) { const r = await retry(async () => { const encoded = file.split('/').map(encodeURIComponent).join('/'); const res = await fetch(RAW + encoded, { headers: { 'User-Agent': 'bww-selfsync' }, signal: AbortSignal.timeout(30000) }); if (!res.ok) throw new Error(`Download ${res.status}: ${file}`); return res; }); return Buffer.from(await r.arrayBuffer()); }
function writeLocal(file, buf) { const target = path.join(ROOT, file); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, buf); }
function removeLocal(file) { try { fs.unlinkSync(path.join(ROOT, file)); } catch (_) {} }
function readSha() { try { return fs.readFileSync(SHA_FILE, 'utf8').trim(); } catch (_) { return ''; } }
function writeSha(sha) { try { writeLocal('.deploy-sha', Buffer.from(sha)); } catch (err) { logger.warn(`Auto-Update: SHA-Datei nicht schreibbar: ${err.message}`); } }
function latestCommitSha() { return gh(`/repos/${OWNER}/${REPO}/commits/${BRANCH}`).then((c) => c.sha); }
async function fullSync() { const sha = await latestCommitSha(); const tree = await gh(`/repos/${OWNER}/${REPO}/git/trees/${sha}?recursive=1`); const files = (tree.tree || []).filter((e) => e.type === 'blob' && !skipped(e.path)); for (const e of files) writeLocal(e.path, await fetchRaw(e.path)); return { sha, count: files.length }; }
async function applyFile(f, touched, needsInstallRef) { if (f.filename === 'package.json' || f.filename === 'package-lock.json') needsInstallRef.value = true; if (f.status === 'removed') { removeLocal(f.filename); touched.push(`-${f.filename}`); return; } if (f.previous_filename && f.previous_filename !== f.filename) removeLocal(f.previous_filename); writeLocal(f.filename, await fetchRaw(f.filename)); touched.push(`+${f.filename}`); }
let busy = false; let errorCount = 0; let intervalHandle = null; let botProcess = null; let initializing = false; let restartDelay = 1000; let stopping = false;
const status = { enabled: false, checks: 0, lastCheckAt: null, lastResult: null, lastCount: 0, lastFiles: [], lastError: null, sha: readSha() || null };
function statusSnapshot() { return { ...status }; }
async function tick() { if (busy) return; busy = true; status.checks += 1; status.lastCheckAt = new Date().toISOString(); try { let applied = 0; let needsInstall = false; let head = ''; const base = readSha(); if (!base) { const r = await fullSync(); applied = r.count; head = r.sha; status.lastResult = 'installed'; status.lastCount = applied; status.lastFiles = [`Erstinstallation: ${applied} Dateien`]; status.sha = head; logger.info(`Auto-Update: Erstinstallation mit ${applied} Dateien (Commit ${head.slice(0, 7)}).`); } else { let cmp = null; try { cmp = await gh(`/repos/${OWNER}/${REPO}/compare/${base}...${BRANCH}`); } catch (err) { if (!/404/.test(String(err.message))) throw err; const r = await fullSync(); applied = r.count; head = r.sha; status.lastResult = 'installed'; status.lastCount = applied; status.lastFiles = [`Erstinstallation: ${applied} Dateien`]; status.sha = head; logger.info(`Auto-Update: Basis unbekannt, Erstinstallation mit ${applied} Dateien (Commit ${head.slice(0, 7)}).`); } if (cmp) { if (!cmp.files || !cmp.files.length) { errorCount = 0; status.lastResult = 'up-to-date'; status.lastCount = 0; status.lastFiles = []; status.lastError = null; status.sha = base; return; } const touched = []; const installRef = { value: false }; for (const f of cmp.files) { if (skipped(f.filename)) continue; await applyFile(f, touched, installRef); } applied = touched.length; needsInstall = installRef.value; head = await latestCommitSha(); if (!applied) { writeSha(head); status.lastResult = 'up-to-date'; status.lastCount = 0; status.lastFiles = []; status.lastError = null; status.sha = head; return; } logger.info(`Auto-Update: ${applied} Datei(en) aktualisiert (${touched.join(', ')}, Commit ${head.slice(0, 7)}).`); status.lastResult = 'updated'; status.lastCount = applied; status.lastFiles = touched; status.sha = head; } } writeSha(head); errorCount = 0; if (needsInstall) { logger.info('Auto-Update: package.json geändert – installiere Abhängigkeiten neu…'); const res = spawnSync('npm', ['install', '--omit=dev', '--no-audit', '--no-fund'], { cwd: ROOT, shell: true, stdio: 'inherit' }); if (res.status !== 0) logger.warn(`Auto-Update: npm install beendet mit Code ${res.status}.`); } logger.info('Auto-Update: Starte neu, um die neue Version zu laden…'); if (initializing) return; stopBot(); setTimeout(() => process.exit(0), 1500).unref(); } catch (err) { errorCount += 1; status.lastResult = 'error'; status.lastError = err.message; logger.error(`Auto-Update fehlgeschlagen (${errorCount}): ${err.stack || err.message}`); if (errorCount >= 5) { logger.error('Auto-Update nach 5 Fehlern deaktiviert – bitte Logs prüfen.'); if (intervalHandle) clearInterval(intervalHandle); } } finally { busy = false; } }
function stopBot() { if (botProcess && !botProcess.killed) { stopping = true; logger.info('Stoppe Bot...'); botProcess.kill('SIGTERM'); botProcess = null; } }
function startBot() { logger.info('Starte Bot (node src/index.js)...'); if (WEBHOOK_URL) logger.info(`Log-Webhook aktiv (Level: ${WEBHOOK_LEVEL})`); stopping = false; botProcess = spawn('node', ['src/index.js'], { cwd: ROOT, env: process.env, stdio: ['ignore', 'pipe', 'pipe'] }); const forward = (stream) => { if (!stream) return; stream.on('data', (buf) => { const text = buf.toString(); const chunk = text.endsWith('\n') ? text : text + '\n'; writeToFile(chunk); if (WEBHOOK_URL) { const level = text.includes('[ERROR]') || text.toLowerCase().includes('error') ? 'ERROR' : text.includes('[WARN]') ? 'WARN' : 'INFO'; notifyWebhook(level, text.trim()); } }); }; forward(botProcess.stdout); forward(botProcess.stderr); botProcess.on('exit', (code, signal) => { logger.info(`Bot-Prozess beendet (code=${code}, signal=${signal})`); botProcess = null; if (!stopping && process.exitCode !== 0) { logger.warn(`Bot unerwartet beendet – starte in ${Math.round(restartDelay / 1000)}s neu…`); const delay = restartDelay; restartDelay = Math.min(restartDelay * 2, 60000); setTimeout(() => { if (!stopping) startBot(); }, delay); } }); botProcess.on('error', (err) => { logger.error('Bot-Fehler:', err.message); }); }
async function start() { try { if (ENABLED) { status.enabled = true; logger.info(`Auto-Update aktiv – prüfe alle ${INTERVAL_S} Sekunden auf neue Commits.`); if (!readSha()) { initializing = true; logger.info('Nichts installiert – starte Erstinstallation...'); await tick(); initializing = false; } } else { logger.info('Auto-Update deaktiviert (AUTO_UPDATE != true).'); } } catch (err) { logger.error('Initialer Auto-Update-Schritt fehlgeschlagen:', err && err.message ? err.message : err); } startBot(); if (ENABLED) { intervalHandle = setInterval(() => tick().catch(() => {}), INTERVAL_MS); } const RESTART_FILE = path.join(ROOT, 'restart.requested'); setInterval(() => { try { if (fs.existsSync(RESTART_FILE)) { try { fs.unlinkSync(RESTART_FILE); } catch (_) {} logger.info('Neustart via restart.requested angefordert – starte neu…'); notifyWebhook('INFO', 'Neustart via restart.requested'); stopBot(); setTimeout(() => process.exit(0), 1500).unref(); } } catch (_) {} }, 3000); }
start();
module.exports = { tick, status: statusSnapshot };
