-- BWW Honeypot module
-- Idempotent schema for the persistent honeypot hit history.

create table if not exists public.bww_honeypot_events (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  channel_id text not null,
  message_id text,
  user_id text not null,
  username text,
  action text not null default 'triggered'
    check (action in ('triggered')),
  punishment text not null default 'none'
    check (punishment in ('none', 'kick', 'ban', 'timeout')),
  punishment_success boolean,
  message_deleted boolean not null default false,
  message_url text,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists bww_honeypot_events_guild_created_idx
  on public.bww_honeypot_events (guild_id, created_at desc);

create index if not exists bww_honeypot_events_user_idx
  on public.bww_honeypot_events (guild_id, user_id);

alter table public.bww_honeypot_events enable row level security;

revoke all on table public.bww_honeypot_events from anon, authenticated;
grant select, insert, update, delete on table public.bww_honeypot_events to service_role;
grant usage, select on sequence public.bww_honeypot_events_id_seq to service_role;
