-- BWW Giveaway system
-- Persistent giveaway records, entries and winner draw history.

create table if not exists public.bww_giveaways (
  id text primary key,
  guild_id text not null,
  channel_id text not null,
  message_id text,
  prize text not null,
  winner_count integer not null default 1 check (winner_count between 1 and 100),
  end_at timestamptz not null,
  status text not null default 'active' check (status in ('active','ended','cancelled')),
  created_by text,
  created_at timestamptz not null default now(),
  ended_at timestamptz,
  current_winners jsonb not null default '[]'::jsonb,
  winner_history jsonb not null default '[]'::jsonb,
  required_role_id text,
  min_account_age_days integer not null default 0 check (min_account_age_days between 0 and 3650),
  min_server_age_days integer not null default 0 check (min_server_age_days between 0 and 3650),
  bonus_entries integer not null default 0 check (bonus_entries between 0 and 20),
  entry_count integer not null default 0 check (entry_count >= 0)
);

create index if not exists bww_giveaways_guild_status_idx
  on public.bww_giveaways (guild_id, status, end_at);

create index if not exists bww_giveaways_end_at_idx
  on public.bww_giveaways (status, end_at);

create table if not exists public.bww_giveaway_entries (
  giveaway_id text not null references public.bww_giveaways(id) on delete cascade,
  user_id text not null,
  entered_at timestamptz not null default now(),
  entry_count integer not null default 1 check (entry_count between 1 and 21),
  primary key (giveaway_id, user_id)
);

create index if not exists bww_giveaway_entries_user_idx
  on public.bww_giveaway_entries (user_id);

create table if not exists public.bww_giveaway_winners (
  id bigint generated by default as identity primary key,
  giveaway_id text not null references public.bww_giveaways(id) on delete cascade,
  user_id text not null,
  draw_type text not null check (draw_type in ('initial','reroll')),
  draw_number integer not null default 1 check (draw_number >= 1),
  created_at timestamptz not null default now()
);

create index if not exists bww_giveaway_winners_giveaway_idx
  on public.bww_giveaway_winners (giveaway_id, created_at desc);

alter table public.bww_giveaways enable row level security;
alter table public.bww_giveaway_entries enable row level security;
alter table public.bww_giveaway_winners enable row level security;

revoke all on table public.bww_giveaways from anon, authenticated;
revoke all on table public.bww_giveaway_entries from anon, authenticated;
revoke all on table public.bww_giveaway_winners from anon, authenticated;

grant select, insert, update, delete on table public.bww_giveaways to service_role;
grant select, insert, update, delete on table public.bww_giveaway_entries to service_role;
grant select, insert, update, delete on table public.bww_giveaway_winners to service_role;
grant usage, select on sequence public.bww_giveaway_winners_id_seq to service_role;
