create table if not exists public.bww_tickets (
  id text primary key,
  guild_id text not null,
  channel_id text,
  owner_id text not null,
  reason text not null,
  description text,
  status text not null default 'open' check (status in ('open','locked','closed')),
  claimed_by text,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  participant_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_by text,
  close_reason text,
  transcript_message_id text,
  log_message_id text
);

create index if not exists bww_tickets_guild_status_idx
  on public.bww_tickets (guild_id, status, updated_at desc);

create index if not exists bww_tickets_owner_idx
  on public.bww_tickets (guild_id, owner_id, status);

create unique index if not exists bww_tickets_open_owner_uidx
  on public.bww_tickets (guild_id, owner_id)
  where status in ('open','locked');

create table if not exists public.bww_ticket_events (
  id bigint generated by default as identity primary key,
  ticket_id text not null references public.bww_tickets(id) on delete cascade,
  guild_id text not null,
  event_type text not null,
  actor_id text,
  target_user_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists bww_ticket_events_ticket_idx
  on public.bww_ticket_events (ticket_id, created_at desc);

create index if not exists bww_ticket_events_guild_idx
  on public.bww_ticket_events (guild_id, created_at desc);

alter table public.bww_tickets enable row level security;
alter table public.bww_ticket_events enable row level security;

revoke all on table public.bww_tickets from anon, authenticated;
revoke all on table public.bww_ticket_events from anon, authenticated;

grant select, insert, update, delete on table public.bww_tickets to service_role;
grant select, insert, update, delete on table public.bww_ticket_events to service_role;
grant usage, select on sequence public.bww_ticket_events_id_seq to service_role;
